language: go
go:
 - 1.9.x
jobs:
  include:
    - stage: Test
      script: go test -race -coverprofile=coverage.txt -covermode=atomic
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: GitHub Release
      script: ./build_release.sh
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        file: binaries.tar.gz
        overwrite: true
        on:
          tags: true

